name: pokemmo
title: PokeMMO
base: core24
version: '4.0e'
summary: PokeMMO Game Client
license: 'Proprietary'
grade: stable
confinement: strict
compression: lzo
description: |
  PokeMMO is an online-only emulator for several popular Nintendo DS & Game Boy Advance games,
  allowing you to play, talk, fight, and trade with other players in realtime across multiple
  platforms.

  This game requires a constant internet connection. Usage of this program requires an account
  with https://pokemmo.com/ and requires you to accept the PokeMMO Terms of Service at login

platforms:
  amd64:
    build-on: amd64
    build-for: amd64
  arm64:
    build-on: arm64
    build-for: arm64

assumes:
  - snapd2.55.5

apps:
  pokemmo:
    command: "./launcher"
    extensions: [ gnome ]
    plugs:
      - network
      - opengl
      - home
      - joystick
      - audio-playback
      - removable-media
    environment:
      XDG_DATA_HOME: "$SNAP/usr/share"
      XDG_CONFIG_HOME: "$XDG_DATA_HOME/.config"
      POKEMMO_IS_SNAPPED: '1'
      __GL_THREADED_OPTIMIZATIONS: '0' # Workaround for NVIDIA proprietary driver issues. See LWJGL/lwjgl3#1071
      LIBDECOR_PLUGIN_DIR: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libdecor/plugins-1

parts:
  pokemmo:
    plugin: dump
    source: https://github.com/PokeMMO/pokemmo-launcher/releases/download/4.0e/build.zip
    source-type: zip
    source-checksum: sha256/3a710805442caab88d502db3ad453690814f1e49a0ec6092923aec5617518fb7
    override-build: |
      case "$CRAFT_ARCH_BUILD_FOR" in
        amd64) cp linux/x64/PokeMMO-Updater $CRAFT_PART_INSTALL/launcher ;;
        arm64) cp linux/arm64/PokeMMO-Updater $CRAFT_PART_INSTALL/launcher ;;
      esac
      chmod +x $CRAFT_PART_INSTALL/launcher
    stage-packages:
      - libglu1-mesa
      - libdecor-0-0
      - libdecor-0-plugin-1-gtk
